/* 1-bpp fonts of the user interface, generated by tools/ui/font_gen.py. */
#ifndef UI_FONTS_H
#define UI_FONTS_H

#include "lvgl.h"

LV_FONT_DECLARE(ui_font_r10)
LV_FONT_DECLARE(ui_font_r12)
LV_FONT_DECLARE(ui_font_b12)
LV_FONT_DECLARE(ui_font_b14)
LV_FONT_DECLARE(ui_font_b16)
LV_FONT_DECLARE(ui_font_b18)
LV_FONT_DECLARE(ui_font_b22)
LV_FONT_DECLARE(ui_font_b28)
LV_FONT_DECLARE(ui_font_b32)
LV_FONT_DECLARE(ui_font_b44)
LV_FONT_DECLARE(ui_font_b64)

#endif /* UI_FONTS_H */
