/*
 * ui_font_r12: 12 px, 1 bpp, 129 glyphs.
 * Generated by tools/ui/font_gen.py from DejaVuSans.ttf; do not edit.
 * DejaVu fonts license: see LICENSE-DejaVu.txt in this folder.
 */

#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0021 '!' */
    0xfd, 0x80,
    /* U+0022 '"' */
    0xb6, 0x80,
    /* U+0023 '#' */
    0x12, 0x14, 0x7f, 0x24, 0x24, 0xfe, 0x28, 0x48,
    /* U+0024 '$' */
    0x23, 0xab, 0x4e, 0x1c, 0xb5, 0x71, 0x08,
    /* U+0025 '%' */
    0x61, 0x24, 0x89, 0x22, 0x50, 0x6d, 0x82, 0x91, 0x24, 0x49, 0x21, 0x80,
    /* U+0026 '&' */
    0x30, 0x48, 0x40, 0x60, 0x51, 0x89, 0x86, 0xc4, 0x7b,
    /* U+0027 ''' */
    0xe0,
    /* U+0028 '(' */
    0x69, 0x49, 0x24, 0x49, 0x80,
    /* U+0029 ')' */
    0xc9, 0x12, 0x49, 0x4b, 0x00,
    /* U+002A */
    0x25, 0x5c, 0xea, 0x90,
    /* U+002B '+' */
    0x10, 0x20, 0x47, 0xf1, 0x02, 0x04, 0x00,
    /* U+002C ',' */
    0xe0,
    /* U+002D '-' */
    0xe0,
    /* U+002E '.' */
    0xc0,
    /* U+002F */
    0x11, 0x22, 0x24, 0x44, 0x88,
    /* U+0030 '0' */
    0x79, 0x28, 0x61, 0x86, 0x18, 0x52, 0x78,
    /* U+0031 '1' */
    0xe1, 0x08, 0x42, 0x10, 0x84, 0xf8,
    /* U+0032 '2' */
    0x7a, 0x30, 0x41, 0x08, 0x42, 0x10, 0xfc,
    /* U+0033 '3' */
    0x7a, 0x10, 0x41, 0x38, 0x10, 0x61, 0x78,
    /* U+0034 '4' */
    0x18, 0x62, 0x92, 0x4a, 0x2f, 0xc2, 0x08,
    /* U+0035 '5' */
    0xfa, 0x08, 0x3e, 0x0c, 0x10, 0x63, 0x78,
    /* U+0036 '6' */
    0x39, 0x18, 0x2e, 0xce, 0x18, 0x53, 0x78,
    /* U+0037 '7' */
    0xfc, 0x10, 0x82, 0x10, 0x42, 0x08, 0x40,
    /* U+0038 '8' */
    0x7a, 0x18, 0x61, 0x7a, 0x18, 0x61, 0x78,
    /* U+0039 '9' */
    0x7b, 0x28, 0x61, 0xcd, 0xd0, 0x62, 0x70,
    /* U+003A ':' */
    0xcc,
    /* U+003B ';' */
    0xce,
    /* U+003C '<' */
    0x03, 0x1e, 0xe0, 0xe0, 0x1e, 0x03,
    /* U+003D '=' */
    0xff, 0x00, 0xff,
    /* U+003E '>' */
    0xc0, 0x78, 0x07, 0x07, 0x78, 0xc0,
    /* U+003F '?' */
    0x74, 0x42, 0x22, 0x10, 0x04, 0x20,
    /* U+0040 '@' */
    0x1f, 0x04, 0x19, 0x01, 0x47, 0x99, 0x13, 0x22, 0x64, 0x54, 0x7c, 0x40, 0x04, 0x10, 0x7c, 0x00,
    /* U+0041 'A' */
    0x18, 0x18, 0x24, 0x24, 0x24, 0x42, 0x7e, 0x42, 0x81,
    /* U+0042 'B' */
    0xfa, 0x18, 0x61, 0xfa, 0x18, 0x61, 0xf8,
    /* U+0043 'C' */
    0x39, 0x18, 0x20, 0x82, 0x08, 0x11, 0x38,
    /* U+0044 'D' */
    0xf9, 0x0a, 0x0c, 0x18, 0x30, 0x60, 0xc2, 0xf8,
    /* U+0045 'E' */
    0xfe, 0x08, 0x20, 0xfe, 0x08, 0x20, 0xfc,
    /* U+0046 'F' */
    0xfc, 0x21, 0x0f, 0xc2, 0x10, 0x80,
    /* U+0047 'G' */
    0x3c, 0x86, 0x04, 0x08, 0xf0, 0x60, 0xa1, 0x3c,
    /* U+0048 'H' */
    0x83, 0x06, 0x0c, 0x1f, 0xf0, 0x60, 0xc1, 0x82,
    /* U+0049 'I' */
    0xff, 0x80,
    /* U+004A 'J' */
    0x24, 0x92, 0x49, 0x27, 0x00,
    /* U+004B 'K' */
    0x86, 0x29, 0x28, 0xc2, 0x89, 0x22, 0x84,
    /* U+004C 'L' */
    0x84, 0x21, 0x08, 0x42, 0x10, 0xf8,
    /* U+004D 'M' */
    0x81, 0xc3, 0xc3, 0xa5, 0xa5, 0x99, 0x99, 0x81, 0x81,
    /* U+004E 'N' */
    0xc3, 0x86, 0x8d, 0x19, 0x31, 0x62, 0xc3, 0x86,
    /* U+004F 'O' */
    0x38, 0x8a, 0x0c, 0x18, 0x30, 0x60, 0xa2, 0x38,
    /* U+0050 'P' */
    0xfa, 0x18, 0x61, 0xfa, 0x08, 0x20, 0x80,
    /* U+0051 'Q' */
    0x38, 0x8a, 0x0c, 0x18, 0x30, 0x60, 0xa2, 0x38, 0x10, 0x10,
    /* U+0052 'R' */
    0xf9, 0x0a, 0x14, 0x2f, 0x91, 0x21, 0x42, 0x82,
    /* U+0053 'S' */
    0x7a, 0x18, 0x20, 0x78, 0x10, 0x61, 0x78,
    /* U+0054 'T' */
    0xfe, 0x20, 0x40, 0x81, 0x02, 0x04, 0x08, 0x10,
    /* U+0055 'U' */
    0x83, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xe3, 0x7c,
    /* U+0056 'V' */
    0x81, 0x81, 0x42, 0x42, 0x42, 0x24, 0x24, 0x18, 0x18,
    /* U+0057 'W' */
    0x84, 0x28, 0x89, 0x11, 0x25, 0x22, 0xa8, 0x55, 0x0a, 0xa0, 0x88, 0x11, 0x00,
    /* U+0058 'X' */
    0xc6, 0x88, 0xa1, 0x41, 0x05, 0x0a, 0x22, 0x82,
    /* U+0059 'Y' */
    0x82, 0x89, 0x11, 0x42, 0x82, 0x04, 0x08, 0x10,
    /* U+005A 'Z' */
    0xfe, 0x04, 0x10, 0x41, 0x04, 0x10, 0x40, 0xfe,
    /* U+005B '[' */
    0xea, 0xaa, 0xac,
    /* U+005C */
    0x88, 0x44, 0x42, 0x22, 0x11,
    /* U+005D ']' */
    0xd5, 0x55, 0x5c,
    /* U+005E '^' */
    0x31, 0x28, 0x40,
    /* U+005F '_' */
    0xfc,
    /* U+0060 '`' */
    0x90,
    /* U+0061 'a' */
    0x7a, 0x10, 0x5f, 0x86, 0x37, 0x40,
    /* U+0062 'b' */
    0x82, 0x08, 0x3e, 0xce, 0x18, 0x61, 0xcf, 0xe0,
    /* U+0063 'c' */
    0x76, 0x61, 0x08, 0x65, 0xc0,
    /* U+0064 'd' */
    0x04, 0x10, 0x5f, 0xce, 0x18, 0x61, 0xcd, 0xf0,
    /* U+0065 'e' */
    0x7b, 0x38, 0x7f, 0x83, 0x17, 0x80,
    /* U+0066 'f' */
    0x34, 0x4f, 0x44, 0x44, 0x44,
    /* U+0067 'g' */
    0x7f, 0x38, 0x61, 0x87, 0x37, 0xc1, 0x4c, 0xe0,
    /* U+0068 'h' */
    0x82, 0x08, 0x2e, 0xc6, 0x18, 0x61, 0x86, 0x10,
    /* U+0069 'i' */
    0xbf, 0x80,
    /* U+006A 'j' */
    0x45, 0x55, 0x57,
    /* U+006B 'k' */
    0x84, 0x21, 0x19, 0x53, 0x14, 0x94, 0x40,
    /* U+006C 'l' */
    0xff, 0xc0,
    /* U+006D 'm' */
    0xf7, 0x44, 0x62, 0x31, 0x18, 0x8c, 0x46, 0x22,
    /* U+006E 'n' */
    0xbb, 0x18, 0x61, 0x86, 0x18, 0x40,
    /* U+006F 'o' */
    0x7b, 0x38, 0x61, 0x87, 0x37, 0x80,
    /* U+0070 'p' */
    0xfb, 0x38, 0x61, 0x87, 0x3f, 0xa0, 0x82, 0x00,
    /* U+0071 'q' */
    0x7f, 0x38, 0x61, 0x87, 0x37, 0xc1, 0x04, 0x10,
    /* U+0072 'r' */
    0xbc, 0x88, 0x88, 0x80,
    /* U+0073 's' */
    0x74, 0x60, 0xe0, 0xc5, 0xc0,
    /* U+0074 't' */
    0x44, 0xf4, 0x44, 0x44, 0x70,
    /* U+0075 'u' */
    0x86, 0x18, 0x61, 0x86, 0x37, 0x40,
    /* U+0076 'v' */
    0x86, 0x14, 0x92, 0x48, 0xc3, 0x00,
    /* U+0077 'w' */
    0x88, 0xc4, 0x55, 0x4a, 0xa5, 0x51, 0x10, 0x88,
    /* U+0078 'x' */
    0x85, 0x24, 0x8c, 0x49, 0x28, 0x40,
    /* U+0079 'y' */
    0x86, 0x14, 0x92, 0x28, 0xc1, 0x04, 0x23, 0x00,
    /* U+007A 'z' */
    0xf8, 0x44, 0x44, 0x43, 0xe0,
    /* U+007B '{' */
    0x39, 0x08, 0x42, 0x60, 0x84, 0x21, 0x0e,
    /* U+007C '|' */
    0xff, 0xf0,
    /* U+007D '}' */
    0xe1, 0x08, 0x42, 0x0c, 0x84, 0x21, 0x38,
    /* U+007E '~' */
    0x71, 0x8e,
    /* U+00B0 '°' */
    0x69, 0x96,
    /* U+00B5 'µ' */
    0x85, 0x0a, 0x14, 0x28, 0x50, 0xbf, 0xc0, 0x81, 0x00,
    /* U+00B7 '·' */
    0xc0,
    /* U+00C0 'À' */
    0x10, 0x08, 0x00, 0x18, 0x18, 0x24, 0x24, 0x24, 0x42, 0x7e, 0x42, 0x81,
    /* U+00C1 'Á' */
    0x08, 0x10, 0x00, 0x18, 0x18, 0x24, 0x24, 0x24, 0x42, 0x7e, 0x42, 0x81,
    /* U+00C2 'Â' */
    0x18, 0x24, 0x00, 0x18, 0x18, 0x24, 0x24, 0x24, 0x42, 0x7e, 0x42, 0x81,
    /* U+00C3 'Ã' */
    0x34, 0x2c, 0x00, 0x18, 0x18, 0x24, 0x24, 0x24, 0x42, 0x7e, 0x42, 0x81,
    /* U+00C7 'Ç' */
    0x39, 0x18, 0x20, 0x82, 0x08, 0x11, 0x38, 0x21, 0x80,
    /* U+00C9 'É' */
    0x10, 0x80, 0x3f, 0x82, 0x08, 0x3f, 0x82, 0x08, 0x3f,
    /* U+00CA 'Ê' */
    0x31, 0x20, 0x3f, 0x82, 0x08, 0x3f, 0x82, 0x08, 0x3f,
    /* U+00CD 'Í' */
    0x62, 0xaa, 0xaa,
    /* U+00D3 'Ó' */
    0x08, 0x20, 0x01, 0xc4, 0x50, 0x60, 0xc1, 0x83, 0x05, 0x11, 0xc0,
    /* U+00D4 'Ô' */
    0x10, 0x50, 0x01, 0xc4, 0x50, 0x60, 0xc1, 0x83, 0x05, 0x11, 0xc0,
    /* U+00D5 'Õ' */
    0x74, 0xb8, 0x01, 0xc4, 0x50, 0x60, 0xc1, 0x83, 0x05, 0x11, 0xc0,
    /* U+00D7 '×' */
    0x82, 0x88, 0xa0, 0x82, 0x88, 0xa0, 0x80,
    /* U+00DA 'Ú' */
    0x10, 0x40, 0x04, 0x18, 0x30, 0x60, 0xc1, 0x83, 0x07, 0x1b, 0xe0,
    /* U+00DC 'Ü' */
    0x28, 0x02, 0x0c, 0x18, 0x30, 0x60, 0xc1, 0x83, 0x8d, 0xf0,
    /* U+00E0 'à' */
    0x20, 0x40, 0x1e, 0x84, 0x17, 0xe1, 0x8d, 0xd0,
    /* U+00E1 'á' */
    0x10, 0x80, 0x1e, 0x84, 0x17, 0xe1, 0x8d, 0xd0,
    /* U+00E2 'â' */
    0x31, 0x20, 0x1e, 0x84, 0x17, 0xe1, 0x8d, 0xd0,
    /* U+00E3 'ã' */
    0x69, 0x60, 0x1e, 0x84, 0x17, 0xe1, 0x8d, 0xd0,
    /* U+00E7 'ç' */
    0x76, 0x61, 0x08, 0x65, 0xc2, 0x30,
    /* U+00E9 'é' */
    0x10, 0x80, 0x1e, 0xce, 0x1f, 0xe0, 0xc5, 0xe0,
    /* U+00EA 'ê' */
    0x31, 0x20, 0x1e, 0xce, 0x1f, 0xe0, 0xc5, 0xe0,
    /* U+00ED 'í' */
    0x62, 0xaa, 0xa0,
    /* U+00F3 'ó' */
    0x10, 0x80, 0x1e, 0xce, 0x18, 0x61, 0xcd, 0xe0,
    /* U+00F4 'ô' */
    0x31, 0x20, 0x1e, 0xce, 0x18, 0x61, 0xcd, 0xe0,
    /* U+00F5 'õ' */
    0x69, 0x60, 0x1e, 0xce, 0x18, 0x61, 0xcd, 0xe0,
    /* U+00FA 'ú' */
    0x10, 0x80, 0x21, 0x86, 0x18, 0x61, 0x8d, 0xd0,
    /* U+00FC 'ü' */
    0x48, 0x08, 0x61, 0x86, 0x18, 0x63, 0x74,
    /* U+2013 '–' */
    0xf8,
    /* U+2014 '—' */
    0xff, 0xe0,
    /* U+2026 '…' */
    0x88, 0xc4, 0x40,
    /* U+2212 '−' */
    0xff,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* id 0: reserved */
    {.bitmap_index = 0, .adv_w = 64, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* U+0020 */
    {.bitmap_index = 0, .adv_w = 80, .box_w = 1, .box_h = 9, .ofs_x = 2, .ofs_y = 0}, /* U+0021 '!' */
    {.bitmap_index = 2, .adv_w = 96, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 6}, /* U+0022 '"' */
    {.bitmap_index = 4, .adv_w = 160, .box_w = 8, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0023 '#' */
    {.bitmap_index = 12, .adv_w = 128, .box_w = 5, .box_h = 11, .ofs_x = 2, .ofs_y = -2}, /* U+0024 '$' */
    {.bitmap_index = 19, .adv_w = 176, .box_w = 10, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0025 '%' */
    {.bitmap_index = 31, .adv_w = 144, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0026 '&' */
    {.bitmap_index = 40, .adv_w = 48, .box_w = 1, .box_h = 3, .ofs_x = 1, .ofs_y = 6}, /* U+0027 ''' */
    {.bitmap_index = 41, .adv_w = 80, .box_w = 3, .box_h = 11, .ofs_x = 1, .ofs_y = -1}, /* U+0028 '(' */
    {.bitmap_index = 46, .adv_w = 80, .box_w = 3, .box_h = 11, .ofs_x = 1, .ofs_y = -1}, /* U+0029 ')' */
    {.bitmap_index = 51, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 3}, /* U+002A */
    {.bitmap_index = 55, .adv_w = 160, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+002B '+' */
    {.bitmap_index = 62, .adv_w = 64, .box_w = 1, .box_h = 3, .ofs_x = 1, .ofs_y = -1}, /* U+002C ',' */
    {.bitmap_index = 63, .adv_w = 64, .box_w = 3, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+002D '-' */
    {.bitmap_index = 64, .adv_w = 64, .box_w = 1, .box_h = 2, .ofs_x = 1, .ofs_y = 0}, /* U+002E '.' */
    {.bitmap_index = 65, .adv_w = 64, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = -1}, /* U+002F */
    {.bitmap_index = 70, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0030 '0' */
    {.bitmap_index = 77, .adv_w = 128, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0031 '1' */
    {.bitmap_index = 83, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0032 '2' */
    {.bitmap_index = 90, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0033 '3' */
    {.bitmap_index = 97, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0034 '4' */
    {.bitmap_index = 104, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0035 '5' */
    {.bitmap_index = 111, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0036 '6' */
    {.bitmap_index = 118, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0037 '7' */
    {.bitmap_index = 125, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0038 '8' */
    {.bitmap_index = 132, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0039 '9' */
    {.bitmap_index = 139, .adv_w = 64, .box_w = 1, .box_h = 6, .ofs_x = 1, .ofs_y = 0}, /* U+003A ':' */
    {.bitmap_index = 140, .adv_w = 64, .box_w = 1, .box_h = 7, .ofs_x = 1, .ofs_y = -1}, /* U+003B ';' */
    {.bitmap_index = 141, .adv_w = 160, .box_w = 8, .box_h = 6, .ofs_x = 1, .ofs_y = 1}, /* U+003C '<' */
    {.bitmap_index = 147, .adv_w = 160, .box_w = 8, .box_h = 3, .ofs_x = 1, .ofs_y = 2}, /* U+003D '=' */
    {.bitmap_index = 150, .adv_w = 160, .box_w = 8, .box_h = 6, .ofs_x = 1, .ofs_y = 1}, /* U+003E '>' */
    {.bitmap_index = 156, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+003F '?' */
    {.bitmap_index = 162, .adv_w = 192, .box_w = 11, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+0040 '@' */
    {.bitmap_index = 178, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0041 'A' */
    {.bitmap_index = 187, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0042 'B' */
    {.bitmap_index = 194, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0043 'C' */
    {.bitmap_index = 201, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0044 'D' */
    {.bitmap_index = 209, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0045 'E' */
    {.bitmap_index = 216, .adv_w = 112, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0046 'F' */
    {.bitmap_index = 222, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0047 'G' */
    {.bitmap_index = 230, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0048 'H' */
    {.bitmap_index = 238, .adv_w = 64, .box_w = 1, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0049 'I' */
    {.bitmap_index = 240, .adv_w = 64, .box_w = 3, .box_h = 11, .ofs_x = -1, .ofs_y = -2}, /* U+004A 'J' */
    {.bitmap_index = 245, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004B 'K' */
    {.bitmap_index = 252, .adv_w = 112, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004C 'L' */
    {.bitmap_index = 258, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004D 'M' */
    {.bitmap_index = 267, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004E 'N' */
    {.bitmap_index = 275, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004F 'O' */
    {.bitmap_index = 283, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0050 'P' */
    {.bitmap_index = 290, .adv_w = 144, .box_w = 7, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+0051 'Q' */
    {.bitmap_index = 300, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0052 'R' */
    {.bitmap_index = 308, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0053 'S' */
    {.bitmap_index = 315, .adv_w = 112, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0054 'T' */
    {.bitmap_index = 323, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0055 'U' */
    {.bitmap_index = 331, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0056 'V' */
    {.bitmap_index = 340, .adv_w = 192, .box_w = 11, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0057 'W' */
    {.bitmap_index = 353, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0058 'X' */
    {.bitmap_index = 361, .adv_w = 112, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0059 'Y' */
    {.bitmap_index = 369, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+005A 'Z' */
    {.bitmap_index = 377, .adv_w = 80, .box_w = 2, .box_h = 11, .ofs_x = 2, .ofs_y = -2}, /* U+005B '[' */
    {.bitmap_index = 380, .adv_w = 64, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = -1}, /* U+005C */
    {.bitmap_index = 385, .adv_w = 80, .box_w = 2, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+005D ']' */
    {.bitmap_index = 388, .adv_w = 160, .box_w = 6, .box_h = 3, .ofs_x = 2, .ofs_y = 6}, /* U+005E '^' */
    {.bitmap_index = 391, .adv_w = 96, .box_w = 6, .box_h = 1, .ofs_x = 0, .ofs_y = -3}, /* U+005F '_' */
    {.bitmap_index = 392, .adv_w = 96, .box_w = 2, .box_h = 2, .ofs_x = 2, .ofs_y = 8}, /* U+0060 '`' */
    {.bitmap_index = 393, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0061 'a' */
    {.bitmap_index = 399, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0062 'b' */
    {.bitmap_index = 407, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0063 'c' */
    {.bitmap_index = 412, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0064 'd' */
    {.bitmap_index = 420, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0065 'e' */
    {.bitmap_index = 426, .adv_w = 64, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+0066 'f' */
    {.bitmap_index = 431, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+0067 'g' */
    {.bitmap_index = 439, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0068 'h' */
    {.bitmap_index = 447, .adv_w = 48, .box_w = 1, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0069 'i' */
    {.bitmap_index = 449, .adv_w = 48, .box_w = 2, .box_h = 12, .ofs_x = 0, .ofs_y = -3}, /* U+006A 'j' */
    {.bitmap_index = 452, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+006B 'k' */
    {.bitmap_index = 459, .adv_w = 48, .box_w = 1, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+006C 'l' */
    {.bitmap_index = 461, .adv_w = 192, .box_w = 9, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+006D 'm' */
    {.bitmap_index = 469, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+006E 'n' */
    {.bitmap_index = 475, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+006F 'o' */
    {.bitmap_index = 481, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+0070 'p' */
    {.bitmap_index = 489, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+0071 'q' */
    {.bitmap_index = 497, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0072 'r' */
    {.bitmap_index = 501, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0073 's' */
    {.bitmap_index = 506, .adv_w = 80, .box_w = 4, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0074 't' */
    {.bitmap_index = 511, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0075 'u' */
    {.bitmap_index = 517, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = -1, .ofs_y = 0}, /* U+0076 'v' */
    {.bitmap_index = 523, .adv_w = 160, .box_w = 9, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0077 'w' */
    {.bitmap_index = 531, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0078 'x' */
    {.bitmap_index = 537, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = -1, .ofs_y = -3}, /* U+0079 'y' */
    {.bitmap_index = 545, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+007A 'z' */
    {.bitmap_index = 550, .adv_w = 128, .box_w = 5, .box_h = 11, .ofs_x = 2, .ofs_y = -2}, /* U+007B '{' */
    {.bitmap_index = 557, .adv_w = 64, .box_w = 1, .box_h = 12, .ofs_x = 2, .ofs_y = -3}, /* U+007C '|' */
    {.bitmap_index = 559, .adv_w = 128, .box_w = 5, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+007D '}' */
    {.bitmap_index = 566, .adv_w = 160, .box_w = 8, .box_h = 2, .ofs_x = 1, .ofs_y = 4}, /* U+007E '~' */
    {.bitmap_index = 568, .adv_w = 96, .box_w = 4, .box_h = 4, .ofs_x = 1, .ofs_y = 5}, /* U+00B0 '°' */
    {.bitmap_index = 570, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+00B5 'µ' */
    {.bitmap_index = 579, .adv_w = 64, .box_w = 1, .box_h = 2, .ofs_x = 1, .ofs_y = 3}, /* U+00B7 '·' */
    {.bitmap_index = 580, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C0 'À' */
    {.bitmap_index = 592, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C1 'Á' */
    {.bitmap_index = 604, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C2 'Â' */
    {.bitmap_index = 616, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C3 'Ã' */
    {.bitmap_index = 628, .adv_w = 128, .box_w = 6, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+00C7 'Ç' */
    {.bitmap_index = 637, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00C9 'É' */
    {.bitmap_index = 646, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00CA 'Ê' */
    {.bitmap_index = 655, .adv_w = 64, .box_w = 2, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00CD 'Í' */
    {.bitmap_index = 658, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00D3 'Ó' */
    {.bitmap_index = 669, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00D4 'Ô' */
    {.bitmap_index = 680, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00D5 'Õ' */
    {.bitmap_index = 691, .adv_w = 160, .box_w = 7, .box_h = 7, .ofs_x = 2, .ofs_y = 0}, /* U+00D7 '×' */
    {.bitmap_index = 698, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00DA 'Ú' */
    {.bitmap_index = 709, .adv_w = 144, .box_w = 7, .box_h = 11, .ofs_x = 1, .ofs_y = 0}, /* U+00DC 'Ü' */
    {.bitmap_index = 719, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E0 'à' */
    {.bitmap_index = 727, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E1 'á' */
    {.bitmap_index = 735, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E2 'â' */
    {.bitmap_index = 743, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E3 'ã' */
    {.bitmap_index = 751, .adv_w = 112, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = -2}, /* U+00E7 'ç' */
    {.bitmap_index = 757, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E9 'é' */
    {.bitmap_index = 765, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00EA 'ê' */
    {.bitmap_index = 773, .adv_w = 48, .box_w = 2, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00ED 'í' */
    {.bitmap_index = 776, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00F3 'ó' */
    {.bitmap_index = 784, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00F4 'ô' */
    {.bitmap_index = 792, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00F5 'õ' */
    {.bitmap_index = 800, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00FA 'ú' */
    {.bitmap_index = 808, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+00FC 'ü' */
    {.bitmap_index = 815, .adv_w = 96, .box_w = 5, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2013 '–' */
    {.bitmap_index = 816, .adv_w = 192, .box_w = 11, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2014 '—' */
    {.bitmap_index = 818, .adv_w = 192, .box_w = 9, .box_h = 2, .ofs_x = 1, .ofs_y = 0}, /* U+2026 '…' */
    {.bitmap_index = 821, .adv_w = 160, .box_w = 8, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2212 '−' */
};

static const uint16_t unicode_list[] = {
    0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008, 0x0009, 0x000a, 0x000b,
    0x000c, 0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e, 0x001f, 0x0020, 0x0021, 0x0022, 0x0023,
    0x0024, 0x0025, 0x0026, 0x0027, 0x0028, 0x0029, 0x002a, 0x002b, 0x002c, 0x002d, 0x002e, 0x002f,
    0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003a, 0x003b,
    0x003c, 0x003d, 0x003e, 0x003f, 0x0040, 0x0041, 0x0042, 0x0043, 0x0044, 0x0045, 0x0046, 0x0047,
    0x0048, 0x0049, 0x004a, 0x004b, 0x004c, 0x004d, 0x004e, 0x004f, 0x0050, 0x0051, 0x0052, 0x0053,
    0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b, 0x005c, 0x005d, 0x005e, 0x0090,
    0x0095, 0x0097, 0x00a0, 0x00a1, 0x00a2, 0x00a3, 0x00a7, 0x00a9, 0x00aa, 0x00ad, 0x00b3, 0x00b4,
    0x00b5, 0x00b7, 0x00ba, 0x00bc, 0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c7, 0x00c9, 0x00ca, 0x00cd,
    0x00d3, 0x00d4, 0x00d5, 0x00da, 0x00dc, 0x1ff3, 0x1ff4, 0x2006, 0x21f2,
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 0x0020, .range_length = 8691, .glyph_id_start = 1, .unicode_list = unicode_list, .glyph_id_ofs_list = NULL, .list_length = 129, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,
    .stride = 0,
};

const lv_font_t ui_font_r12 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 15,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};
