/*
 * ui_font_b12: 12 px, 1 bpp, 129 glyphs.
 * Generated by tools/ui/font_gen.py from DejaVuSans-Bold.ttf; do not edit.
 * DejaVu fonts license: see LICENSE-DejaVu.txt in this folder.
 */

#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0021 '!' */
    0xff, 0xf3, 0xc0,
    /* U+0022 '"' */
    0xb6, 0x80,
    /* U+0023 '#' */
    0x12, 0x16, 0x7f, 0x24, 0x24, 0xfe, 0x68, 0x68, 0x48,
    /* U+0024 '$' */
    0x10, 0xfb, 0x47, 0x8f, 0xcf, 0xc7, 0x8b, 0xfc, 0x20, 0x40,
    /* U+0025 '%' */
    0x71, 0x11, 0x22, 0x28, 0x47, 0x07, 0x5c, 0x1c, 0x42, 0x88, 0x91, 0x11, 0xc0,
    /* U+0026 '&' */
    0x38, 0x32, 0x18, 0x06, 0x07, 0x9e, 0xef, 0x3d, 0x8e, 0x7d, 0x80,
    /* U+0027 ''' */
    0xe0,
    /* U+0028 '(' */
    0x76, 0x6c, 0xcc, 0xcc, 0x66, 0x70,
    /* U+0029 ')' */
    0xe6, 0x63, 0x33, 0x33, 0x66, 0xe0,
    /* U+002A */
    0x25, 0x5c, 0xea, 0x90,
    /* U+002B '+' */
    0x10, 0x20, 0x47, 0xf1, 0x02, 0x04, 0x00,
    /* U+002C ',' */
    0x6d, 0x40,
    /* U+002D '-' */
    0xff,
    /* U+002E '.' */
    0xf0,
    /* U+002F */
    0x13, 0x22, 0x24, 0x44, 0xc8,
    /* U+0030 '0' */
    0x38, 0xdb, 0x1e, 0x3c, 0x78, 0xf1, 0xb6, 0x38,
    /* U+0031 '1' */
    0xf0, 0xc3, 0x0c, 0x30, 0xc3, 0x0c, 0xfc,
    /* U+0032 '2' */
    0x7d, 0x0c, 0x18, 0x30, 0xc3, 0x0c, 0x30, 0xfe,
    /* U+0033 '3' */
    0x7d, 0x0c, 0x18, 0x33, 0xc0, 0xc1, 0xc3, 0x7c,
    /* U+0034 '4' */
    0x1c, 0x78, 0xb2, 0x6c, 0xd1, 0xbf, 0x86, 0x0c,
    /* U+0035 '5' */
    0xfd, 0x83, 0x07, 0xe0, 0xe0, 0xc1, 0x87, 0xfc,
    /* U+0036 '6' */
    0x3c, 0xc3, 0x07, 0xec, 0x78, 0xf1, 0xa3, 0x3c,
    /* U+0037 '7' */
    0xfe, 0x0c, 0x30, 0x61, 0x83, 0x0c, 0x18, 0x60,
    /* U+0038 '8' */
    0x7d, 0x8f, 0x1e, 0x33, 0x98, 0xf1, 0xe3, 0x7c,
    /* U+0039 '9' */
    0x79, 0x8b, 0x1e, 0x3c, 0x6f, 0xc1, 0x86, 0x78,
    /* U+003A ':' */
    0xf0, 0x3c,
    /* U+003B ';' */
    0x6c, 0x00, 0xda, 0x80,
    /* U+003C '<' */
    0x01, 0x0f, 0x78, 0xc0, 0x78, 0x0f, 0x01,
    /* U+003D '=' */
    0xff, 0x00, 0xff,
    /* U+003E '>' */
    0x80, 0xf0, 0x1e, 0x03, 0x1e, 0xf0, 0x80,
    /* U+003F '?' */
    0xf0, 0xc6, 0x66, 0x30, 0x0c, 0x60,
    /* U+0040 '@' */
    0x1e, 0x08, 0x64, 0x0a, 0x39, 0x92, 0x64, 0x99, 0x2e, 0x3e, 0x40, 0x08, 0x41, 0xf8,
    /* U+0041 'A' */
    0x1c, 0x0e, 0x0d, 0x86, 0xc3, 0x63, 0x19, 0xfc, 0xc6, 0xc1, 0x80,
    /* U+0042 'B' */
    0xfd, 0x8f, 0x1e, 0x3f, 0xd8, 0xf1, 0xe3, 0xfc,
    /* U+0043 'C' */
    0x3e, 0xc7, 0x06, 0x0c, 0x18, 0x30, 0x31, 0x3e,
    /* U+0044 'D' */
    0xfc, 0xc6, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc6, 0xfc,
    /* U+0045 'E' */
    0xff, 0x0c, 0x30, 0xff, 0x0c, 0x30, 0xfc,
    /* U+0046 'F' */
    0xff, 0x0c, 0x30, 0xff, 0x0c, 0x30, 0xc0,
    /* U+0047 'G' */
    0x3f, 0x61, 0xc0, 0xc0, 0xc7, 0xc3, 0xc3, 0x63, 0x3f,
    /* U+0048 'H' */
    0xc3, 0xc3, 0xc3, 0xc3, 0xff, 0xc3, 0xc3, 0xc3, 0xc3,
    /* U+0049 'I' */
    0xff, 0xff, 0xc0,
    /* U+004A 'J' */
    0x33, 0x33, 0x33, 0x33, 0x33, 0xe0,
    /* U+004B 'K' */
    0xc3, 0xc6, 0xcc, 0xd8, 0xf0, 0xd8, 0xcc, 0xc6, 0xc3,
    /* U+004C 'L' */
    0xc3, 0x0c, 0x30, 0xc3, 0x0c, 0x30, 0xfc,
    /* U+004D 'M' */
    0xe1, 0xf8, 0x7f, 0x3f, 0x4b, 0xde, 0xf3, 0x3c, 0xcf, 0x03, 0xc0, 0xc0,
    /* U+004E 'N' */
    0xe3, 0xe3, 0xf3, 0xd3, 0xdb, 0xcb, 0xcf, 0xc7, 0xc7,
    /* U+004F 'O' */
    0x3e, 0x31, 0xb0, 0x78, 0x3c, 0x1e, 0x0f, 0x06, 0xc6, 0x3e, 0x00,
    /* U+0050 'P' */
    0xfd, 0x8f, 0x1e, 0x3c, 0x7f, 0xb0, 0x60, 0xc0,
    /* U+0051 'Q' */
    0x3e, 0x31, 0xb0, 0x78, 0x3c, 0x1e, 0x0f, 0x06, 0xc6, 0x3e, 0x03, 0x00, 0xc0,
    /* U+0052 'R' */
    0xfc, 0xc6, 0xc6, 0xc6, 0xfc, 0xcc, 0xc6, 0xc6, 0xc3,
    /* U+0053 'S' */
    0x7d, 0x8b, 0x07, 0x87, 0xc1, 0xc1, 0xc3, 0xfc,
    /* U+0054 'T' */
    0xff, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+0055 'U' */
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x7e,
    /* U+0056 'V' */
    0xc1, 0xb1, 0x98, 0xcc, 0x63, 0x61, 0xb0, 0xd8, 0x38, 0x1c, 0x00,
    /* U+0057 'W' */
    0xc6, 0x3c, 0x63, 0x6f, 0x66, 0xf6, 0x69, 0x67, 0x9e, 0x39, 0xc3, 0x0c, 0x30, 0xc0,
    /* U+0058 'X' */
    0xc1, 0xb1, 0x8d, 0x86, 0xc1, 0xc1, 0xb0, 0xd8, 0xc6, 0xc1, 0x80,
    /* U+0059 'Y' */
    0xc3, 0x66, 0x66, 0x3c, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+005A 'Z' */
    0xff, 0x03, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xc0, 0xff,
    /* U+005B '[' */
    0xfc, 0xcc, 0xcc, 0xcc, 0xcc, 0xf0,
    /* U+005C */
    0x8c, 0x44, 0x42, 0x22, 0x31,
    /* U+005D ']' */
    0xf3, 0x33, 0x33, 0x33, 0x33, 0xf0,
    /* U+005E '^' */
    0x31, 0xe8, 0x40,
    /* U+005F '_' */
    0xfc,
    /* U+0060 '`' */
    0xcc,
    /* U+0061 'a' */
    0x3c, 0x8c, 0x1b, 0xfc, 0x78, 0xdf, 0x80,
    /* U+0062 'b' */
    0xc1, 0x83, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0xf8,
    /* U+0063 'c' */
    0x39, 0x9c, 0x30, 0xc1, 0x93, 0x80,
    /* U+0064 'd' */
    0x06, 0x0c, 0x1b, 0xfc, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+0065 'e' */
    0x3c, 0xcb, 0x1f, 0xfc, 0x0c, 0x4f, 0x00,
    /* U+0066 'f' */
    0x3b, 0x19, 0xf6, 0x31, 0x8c, 0x63, 0x00,
    /* U+0067 'g' */
    0x7f, 0xdf, 0x1e, 0x3c, 0x79, 0xdf, 0x83, 0x46, 0x78,
    /* U+0068 'h' */
    0xc1, 0x83, 0x07, 0xee, 0x78, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+0069 'i' */
    0xf3, 0xff, 0xf0,
    /* U+006A 'j' */
    0x6c, 0x36, 0xdb, 0x6d, 0xbc,
    /* U+006B 'k' */
    0xc1, 0x83, 0x06, 0x6d, 0x9e, 0x3c, 0x6c, 0xcd, 0x8c,
    /* U+006C 'l' */
    0xff, 0xff, 0xf0,
    /* U+006D 'm' */
    0xff, 0xb3, 0x3c, 0xcf, 0x33, 0xcc, 0xf3, 0x3c, 0xcc,
    /* U+006E 'n' */
    0xfd, 0xcf, 0x1e, 0x3c, 0x78, 0xf1, 0x80,
    /* U+006F 'o' */
    0x7d, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x00,
    /* U+0070 'p' */
    0xfd, 0x8f, 0x1e, 0x3c, 0x78, 0xff, 0x60, 0xc1, 0x80,
    /* U+0071 'q' */
    0x7f, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x83, 0x06, 0x0c,
    /* U+0072 'r' */
    0xff, 0x31, 0x8c, 0x63, 0x00,
    /* U+0073 's' */
    0x7b, 0x1c, 0x1e, 0x0e, 0x37, 0x80,
    /* U+0074 't' */
    0x63, 0x3e, 0xc6, 0x31, 0x8c, 0x78,
    /* U+0075 'u' */
    0xc7, 0x8f, 0x1e, 0x3c, 0x79, 0xdf, 0x80,
    /* U+0076 'v' */
    0xc7, 0x8d, 0xb3, 0x66, 0xc7, 0x0e, 0x00,
    /* U+0077 'w' */
    0xcc, 0xf3, 0x3d, 0xed, 0x7a, 0x73, 0x9c, 0xe3, 0x30,
    /* U+0078 'x' */
    0xc6, 0xd8, 0xe1, 0xc3, 0x8d, 0xb1, 0x80,
    /* U+0079 'y' */
    0xc7, 0x8d, 0xb3, 0x63, 0xc7, 0x06, 0x0c, 0x30, 0xc0,
    /* U+007A 'z' */
    0xfc, 0x31, 0x8c, 0x63, 0x0f, 0xc0,
    /* U+007B '{' */
    0x1c, 0xc3, 0x0c, 0x33, 0x83, 0x0c, 0x30, 0xc1, 0xc0,
    /* U+007C '|' */
    0xff, 0xf0,
    /* U+007D '}' */
    0xe0, 0xc3, 0x0c, 0x30, 0x73, 0x0c, 0x30, 0xce, 0x00,
    /* U+007E '~' */
    0x71, 0x8e,
    /* U+00B0 '°' */
    0x69, 0x96,
    /* U+00B5 'µ' */
    0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xff, 0xc0, 0xc0, 0xc0,
    /* U+00B7 '·' */
    0xf0,
    /* U+00C0 'À' */
    0x18, 0x06, 0x00, 0x03, 0x81, 0xc1, 0xb0, 0xd8, 0x6c, 0x63, 0x3f, 0x98, 0xd8, 0x30,
    /* U+00C1 'Á' */
    0x06, 0x06, 0x00, 0x03, 0x81, 0xc1, 0xb0, 0xd8, 0x6c, 0x63, 0x3f, 0x98, 0xd8, 0x30,
    /* U+00C2 'Â' */
    0x1c, 0x0a, 0x00, 0x03, 0x81, 0xc1, 0xb0, 0xd8, 0x6c, 0x63, 0x3f, 0x98, 0xd8, 0x30,
    /* U+00C3 'Ã' */
    0x3a, 0x17, 0x00, 0x03, 0x81, 0xc1, 0xb0, 0xd8, 0x6c, 0x63, 0x3f, 0x98, 0xd8, 0x30,
    /* U+00C7 'Ç' */
    0x3e, 0xc7, 0x06, 0x0c, 0x18, 0x30, 0x31, 0x3e, 0x08, 0x70,
    /* U+00C9 'É' */
    0x18, 0xc0, 0x3f, 0xc3, 0x0c, 0x3f, 0xc3, 0x0c, 0x3f,
    /* U+00CA 'Ê' */
    0x31, 0x20, 0x3f, 0xc3, 0x0c, 0x3f, 0xc3, 0x0c, 0x3f,
    /* U+00CD 'Í' */
    0x78, 0x6d, 0xb6, 0xdb, 0x60,
    /* U+00D3 'Ó' */
    0x0c, 0x0c, 0x00, 0x07, 0xc6, 0x36, 0x0f, 0x07, 0x83, 0xc1, 0xe0, 0xd8, 0xc7, 0xc0,
    /* U+00D4 'Ô' */
    0x18, 0x12, 0x00, 0x07, 0xc6, 0x36, 0x0f, 0x07, 0x83, 0xc1, 0xe0, 0xd8, 0xc7, 0xc0,
    /* U+00D5 'Õ' */
    0x1c, 0x0e, 0x00, 0x07, 0xc6, 0x36, 0x0f, 0x07, 0x83, 0xc1, 0xe0, 0xd8, 0xc7, 0xc0,
    /* U+00D7 '×' */
    0x82, 0x88, 0xa0, 0x82, 0x88, 0xa0, 0x80,
    /* U+00DA 'Ú' */
    0x0c, 0x18, 0x00, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x7e,
    /* U+00DC 'Ü' */
    0x24, 0x00, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0x7e,
    /* U+00E0 'à' */
    0x60, 0x60, 0x01, 0xe4, 0x60, 0xdf, 0xe3, 0xc6, 0xfc,
    /* U+00E1 'á' */
    0x18, 0x60, 0x01, 0xe4, 0x60, 0xdf, 0xe3, 0xc6, 0xfc,
    /* U+00E2 'â' */
    0x30, 0x90, 0x01, 0xe4, 0x60, 0xdf, 0xe3, 0xc6, 0xfc,
    /* U+00E3 'ã' */
    0x34, 0x58, 0x01, 0xe4, 0x60, 0xdf, 0xe3, 0xc6, 0xfc,
    /* U+00E7 'ç' */
    0x39, 0x9c, 0x30, 0xc1, 0x93, 0x82, 0x38,
    /* U+00E9 'é' */
    0x18, 0x60, 0x01, 0xe6, 0x58, 0xff, 0xe0, 0x62, 0x78,
    /* U+00EA 'ê' */
    0x30, 0x90, 0x01, 0xe6, 0x58, 0xff, 0xe0, 0x62, 0x78,
    /* U+00ED 'í' */
    0x78, 0x6d, 0xb6, 0xd8,
    /* U+00F3 'ó' */
    0x18, 0x60, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F4 'ô' */
    0x10, 0x50, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F5 'õ' */
    0x74, 0xb8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00FA 'ú' */
    0x18, 0x60, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xce, 0xfc,
    /* U+00FC 'ü' */
    0x28, 0x03, 0x1e, 0x3c, 0x78, 0xf1, 0xe7, 0x7e,
    /* U+2013 '–' */
    0xf8,
    /* U+2014 '—' */
    0xff, 0xe0,
    /* U+2026 '…' */
    0xcc, 0xf3, 0x30,
    /* U+2212 '−' */
    0xff,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* id 0: reserved */
    {.bitmap_index = 0, .adv_w = 64, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* U+0020 */
    {.bitmap_index = 0, .adv_w = 80, .box_w = 2, .box_h = 9, .ofs_x = 2, .ofs_y = 0}, /* U+0021 '!' */
    {.bitmap_index = 3, .adv_w = 96, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 6}, /* U+0022 '"' */
    {.bitmap_index = 5, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0023 '#' */
    {.bitmap_index = 14, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+0024 '$' */
    {.bitmap_index = 24, .adv_w = 192, .box_w = 11, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0025 '%' */
    {.bitmap_index = 37, .adv_w = 160, .box_w = 9, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0026 '&' */
    {.bitmap_index = 48, .adv_w = 64, .box_w = 1, .box_h = 3, .ofs_x = 1, .ofs_y = 6}, /* U+0027 ''' */
    {.bitmap_index = 49, .adv_w = 80, .box_w = 4, .box_h = 11, .ofs_x = 1, .ofs_y = -1}, /* U+0028 '(' */
    {.bitmap_index = 55, .adv_w = 80, .box_w = 4, .box_h = 11, .ofs_x = 0, .ofs_y = -1}, /* U+0029 ')' */
    {.bitmap_index = 61, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 3}, /* U+002A */
    {.bitmap_index = 65, .adv_w = 160, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+002B '+' */
    {.bitmap_index = 72, .adv_w = 80, .box_w = 3, .box_h = 4, .ofs_x = 0, .ofs_y = -2}, /* U+002C ',' */
    {.bitmap_index = 74, .adv_w = 80, .box_w = 4, .box_h = 2, .ofs_x = 1, .ofs_y = 2}, /* U+002D '-' */
    {.bitmap_index = 75, .adv_w = 80, .box_w = 2, .box_h = 2, .ofs_x = 1, .ofs_y = 0}, /* U+002E '.' */
    {.bitmap_index = 76, .adv_w = 64, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = -1}, /* U+002F */
    {.bitmap_index = 81, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0030 '0' */
    {.bitmap_index = 89, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0031 '1' */
    {.bitmap_index = 96, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0032 '2' */
    {.bitmap_index = 104, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0033 '3' */
    {.bitmap_index = 112, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0034 '4' */
    {.bitmap_index = 120, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0035 '5' */
    {.bitmap_index = 128, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0036 '6' */
    {.bitmap_index = 136, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0037 '7' */
    {.bitmap_index = 144, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0038 '8' */
    {.bitmap_index = 152, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0039 '9' */
    {.bitmap_index = 160, .adv_w = 80, .box_w = 2, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+003A ':' */
    {.bitmap_index = 162, .adv_w = 80, .box_w = 3, .box_h = 9, .ofs_x = 0, .ofs_y = -2}, /* U+003B ';' */
    {.bitmap_index = 166, .adv_w = 160, .box_w = 8, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+003C '<' */
    {.bitmap_index = 173, .adv_w = 160, .box_w = 8, .box_h = 3, .ofs_x = 1, .ofs_y = 2}, /* U+003D '=' */
    {.bitmap_index = 176, .adv_w = 160, .box_w = 8, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+003E '>' */
    {.bitmap_index = 183, .adv_w = 112, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+003F '?' */
    {.bitmap_index = 189, .adv_w = 192, .box_w = 10, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+0040 '@' */
    {.bitmap_index = 203, .adv_w = 144, .box_w = 9, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0041 'A' */
    {.bitmap_index = 214, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0042 'B' */
    {.bitmap_index = 222, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0043 'C' */
    {.bitmap_index = 230, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0044 'D' */
    {.bitmap_index = 239, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0045 'E' */
    {.bitmap_index = 246, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0046 'F' */
    {.bitmap_index = 253, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0047 'G' */
    {.bitmap_index = 262, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0048 'H' */
    {.bitmap_index = 271, .adv_w = 64, .box_w = 2, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0049 'I' */
    {.bitmap_index = 274, .adv_w = 64, .box_w = 4, .box_h = 11, .ofs_x = -1, .ofs_y = -2}, /* U+004A 'J' */
    {.bitmap_index = 280, .adv_w = 144, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004B 'K' */
    {.bitmap_index = 289, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004C 'L' */
    {.bitmap_index = 296, .adv_w = 192, .box_w = 10, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004D 'M' */
    {.bitmap_index = 308, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004E 'N' */
    {.bitmap_index = 317, .adv_w = 160, .box_w = 9, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+004F 'O' */
    {.bitmap_index = 328, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0050 'P' */
    {.bitmap_index = 336, .adv_w = 160, .box_w = 9, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+0051 'Q' */
    {.bitmap_index = 349, .adv_w = 144, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0052 'R' */
    {.bitmap_index = 358, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0053 'S' */
    {.bitmap_index = 366, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0054 'T' */
    {.bitmap_index = 375, .adv_w = 160, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0055 'U' */
    {.bitmap_index = 384, .adv_w = 144, .box_w = 9, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0056 'V' */
    {.bitmap_index = 395, .adv_w = 208, .box_w = 12, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+0057 'W' */
    {.bitmap_index = 409, .adv_w = 144, .box_w = 9, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0058 'X' */
    {.bitmap_index = 420, .adv_w = 144, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0059 'Y' */
    {.bitmap_index = 429, .adv_w = 144, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+005A 'Z' */
    {.bitmap_index = 438, .adv_w = 80, .box_w = 4, .box_h = 11, .ofs_x = 1, .ofs_y = -1}, /* U+005B '[' */
    {.bitmap_index = 444, .adv_w = 64, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = -1}, /* U+005C */
    {.bitmap_index = 449, .adv_w = 80, .box_w = 4, .box_h = 11, .ofs_x = 0, .ofs_y = -1}, /* U+005D ']' */
    {.bitmap_index = 455, .adv_w = 160, .box_w = 6, .box_h = 3, .ofs_x = 2, .ofs_y = 6}, /* U+005E '^' */
    {.bitmap_index = 458, .adv_w = 96, .box_w = 6, .box_h = 1, .ofs_x = 0, .ofs_y = -3}, /* U+005F '_' */
    {.bitmap_index = 459, .adv_w = 96, .box_w = 3, .box_h = 2, .ofs_x = 1, .ofs_y = 8}, /* U+0060 '`' */
    {.bitmap_index = 460, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0061 'a' */
    {.bitmap_index = 467, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0062 'b' */
    {.bitmap_index = 476, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0063 'c' */
    {.bitmap_index = 482, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0064 'd' */
    {.bitmap_index = 491, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0065 'e' */
    {.bitmap_index = 498, .adv_w = 80, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+0066 'f' */
    {.bitmap_index = 505, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+0067 'g' */
    {.bitmap_index = 514, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0068 'h' */
    {.bitmap_index = 523, .adv_w = 64, .box_w = 2, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+0069 'i' */
    {.bitmap_index = 526, .adv_w = 64, .box_w = 3, .box_h = 13, .ofs_x = 0, .ofs_y = -3}, /* U+006A 'j' */
    {.bitmap_index = 531, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+006B 'k' */
    {.bitmap_index = 540, .adv_w = 64, .box_w = 2, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+006C 'l' */
    {.bitmap_index = 543, .adv_w = 208, .box_w = 10, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+006D 'm' */
    {.bitmap_index = 552, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+006E 'n' */
    {.bitmap_index = 559, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+006F 'o' */
    {.bitmap_index = 566, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+0070 'p' */
    {.bitmap_index = 575, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+0071 'q' */
    {.bitmap_index = 584, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0072 'r' */
    {.bitmap_index = 589, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0073 's' */
    {.bitmap_index = 595, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = 0}, /* U+0074 't' */
    {.bitmap_index = 601, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0075 'u' */
    {.bitmap_index = 608, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = -1, .ofs_y = 0}, /* U+0076 'v' */
    {.bitmap_index = 615, .adv_w = 176, .box_w = 10, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0077 'w' */
    {.bitmap_index = 624, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0078 'x' */
    {.bitmap_index = 631, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = -1, .ofs_y = -3}, /* U+0079 'y' */
    {.bitmap_index = 640, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+007A 'z' */
    {.bitmap_index = 646, .adv_w = 144, .box_w = 6, .box_h = 11, .ofs_x = 1, .ofs_y = -1}, /* U+007B '{' */
    {.bitmap_index = 655, .adv_w = 64, .box_w = 1, .box_h = 12, .ofs_x = 2, .ofs_y = -3}, /* U+007C '|' */
    {.bitmap_index = 657, .adv_w = 144, .box_w = 6, .box_h = 11, .ofs_x = 1, .ofs_y = -1}, /* U+007D '}' */
    {.bitmap_index = 666, .adv_w = 160, .box_w = 8, .box_h = 2, .ofs_x = 1, .ofs_y = 4}, /* U+007E '~' */
    {.bitmap_index = 668, .adv_w = 96, .box_w = 4, .box_h = 4, .ofs_x = 1, .ofs_y = 5}, /* U+00B0 '°' */
    {.bitmap_index = 670, .adv_w = 144, .box_w = 8, .box_h = 10, .ofs_x = 1, .ofs_y = -3}, /* U+00B5 'µ' */
    {.bitmap_index = 680, .adv_w = 80, .box_w = 2, .box_h = 2, .ofs_x = 1, .ofs_y = 3}, /* U+00B7 '·' */
    {.bitmap_index = 681, .adv_w = 144, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C0 'À' */
    {.bitmap_index = 695, .adv_w = 144, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C1 'Á' */
    {.bitmap_index = 709, .adv_w = 144, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C2 'Â' */
    {.bitmap_index = 723, .adv_w = 144, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = 0}, /* U+00C3 'Ã' */
    {.bitmap_index = 737, .adv_w = 144, .box_w = 7, .box_h = 11, .ofs_x = 1, .ofs_y = -2}, /* U+00C7 'Ç' */
    {.bitmap_index = 747, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00C9 'É' */
    {.bitmap_index = 756, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00CA 'Ê' */
    {.bitmap_index = 765, .adv_w = 64, .box_w = 3, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00CD 'Í' */
    {.bitmap_index = 770, .adv_w = 160, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00D3 'Ó' */
    {.bitmap_index = 784, .adv_w = 160, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00D4 'Ô' */
    {.bitmap_index = 798, .adv_w = 160, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00D5 'Õ' */
    {.bitmap_index = 812, .adv_w = 160, .box_w = 7, .box_h = 7, .ofs_x = 2, .ofs_y = 0}, /* U+00D7 '×' */
    {.bitmap_index = 819, .adv_w = 160, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0}, /* U+00DA 'Ú' */
    {.bitmap_index = 831, .adv_w = 160, .box_w = 8, .box_h = 11, .ofs_x = 1, .ofs_y = 0}, /* U+00DC 'Ü' */
    {.bitmap_index = 842, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E0 'à' */
    {.bitmap_index = 851, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E1 'á' */
    {.bitmap_index = 860, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E2 'â' */
    {.bitmap_index = 869, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E3 'ã' */
    {.bitmap_index = 878, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = -2}, /* U+00E7 'ç' */
    {.bitmap_index = 885, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00E9 'é' */
    {.bitmap_index = 894, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00EA 'ê' */
    {.bitmap_index = 903, .adv_w = 64, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00ED 'í' */
    {.bitmap_index = 907, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00F3 'ó' */
    {.bitmap_index = 916, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00F4 'ô' */
    {.bitmap_index = 925, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00F5 'õ' */
    {.bitmap_index = 934, .adv_w = 144, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00FA 'ú' */
    {.bitmap_index = 943, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+00FC 'ü' */
    {.bitmap_index = 951, .adv_w = 96, .box_w = 5, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2013 '–' */
    {.bitmap_index = 952, .adv_w = 192, .box_w = 11, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2014 '—' */
    {.bitmap_index = 954, .adv_w = 192, .box_w = 10, .box_h = 2, .ofs_x = 1, .ofs_y = 0}, /* U+2026 '…' */
    {.bitmap_index = 957, .adv_w = 160, .box_w = 8, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2212 '−' */
};

static const uint16_t unicode_list[] = {
    0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008, 0x0009, 0x000a, 0x000b,
    0x000c, 0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e, 0x001f, 0x0020, 0x0021, 0x0022, 0x0023,
    0x0024, 0x0025, 0x0026, 0x0027, 0x0028, 0x0029, 0x002a, 0x002b, 0x002c, 0x002d, 0x002e, 0x002f,
    0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003a, 0x003b,
    0x003c, 0x003d, 0x003e, 0x003f, 0x0040, 0x0041, 0x0042, 0x0043, 0x0044, 0x0045, 0x0046, 0x0047,
    0x0048, 0x0049, 0x004a, 0x004b, 0x004c, 0x004d, 0x004e, 0x004f, 0x0050, 0x0051, 0x0052, 0x0053,
    0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b, 0x005c, 0x005d, 0x005e, 0x0090,
    0x0095, 0x0097, 0x00a0, 0x00a1, 0x00a2, 0x00a3, 0x00a7, 0x00a9, 0x00aa, 0x00ad, 0x00b3, 0x00b4,
    0x00b5, 0x00b7, 0x00ba, 0x00bc, 0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c7, 0x00c9, 0x00ca, 0x00cd,
    0x00d3, 0x00d4, 0x00d5, 0x00da, 0x00dc, 0x1ff3, 0x1ff4, 0x2006, 0x21f2,
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 0x0020, .range_length = 8691, .glyph_id_start = 1, .unicode_list = unicode_list, .glyph_id_ofs_list = NULL, .list_length = 129, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,
    .stride = 0,
};

const lv_font_t ui_font_b12 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 15,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};
