/*
 * ui_font_r10: 10 px, 1 bpp, 129 glyphs.
 * Generated by tools/ui/font_gen.py from DejaVuSans.ttf; do not edit.
 * DejaVu fonts license: see LICENSE-DejaVu.txt in this folder.
 */

#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0021 '!' */
    0xfa,
    /* U+0022 '"' */
    0xb6, 0x80,
    /* U+0023 '#' */
    0x24, 0x49, 0xf9, 0x4f, 0xc9, 0x12, 0x00,
    /* U+0024 '$' */
    0x23, 0xe9, 0xc3, 0x97, 0xc4,
    /* U+0025 '%' */
    0xe4, 0xa4, 0xa8, 0xff, 0x15, 0x25, 0x27,
    /* U+0026 '&' */
    0x30, 0x91, 0x05, 0x98, 0xb9, 0x9c, 0x80,
    /* U+0027 ''' */
    0xe0,
    /* U+0028 '(' */
    0x6a, 0xaa, 0x40,
    /* U+0029 ')' */
    0xa5, 0x56, 0x80,
    /* U+002A */
    0xab, 0x9d, 0x50,
    /* U+002B '+' */
    0x10, 0x20, 0x47, 0xf1, 0x02, 0x04, 0x00,
    /* U+002C ',' */
    0xc0,
    /* U+002D '-' */
    0xe0,
    /* U+002E '.' */
    0x80,
    /* U+002F */
    0x25, 0x24, 0xa4,
    /* U+0030 '0' */
    0x74, 0x63, 0x18, 0xc5, 0xc0,
    /* U+0031 '1' */
    0xe1, 0x08, 0x42, 0x13, 0xe0,
    /* U+0032 '2' */
    0x74, 0x42, 0x22, 0x23, 0xe0,
    /* U+0033 '3' */
    0x74, 0x42, 0xe0, 0xc5, 0xc0,
    /* U+0034 '4' */
    0x11, 0x95, 0x2f, 0x88, 0x40,
    /* U+0035 '5' */
    0xf4, 0x3c, 0x10, 0x87, 0xc0,
    /* U+0036 '6' */
    0x7e, 0x21, 0xe8, 0xc5, 0xc0,
    /* U+0037 '7' */
    0xf8, 0x44, 0x22, 0x11, 0x00,
    /* U+0038 '8' */
    0x74, 0x62, 0xe8, 0xc5, 0xc0,
    /* U+0039 '9' */
    0x74, 0x62, 0xf0, 0x8f, 0xc0,
    /* U+003A ':' */
    0x88,
    /* U+003B ';' */
    0x8c,
    /* U+003C '<' */
    0x04, 0xec, 0x0e, 0x04,
    /* U+003D '=' */
    0xfc, 0x0f, 0xc0,
    /* U+003E '>' */
    0x81, 0xc0, 0xdc, 0x80,
    /* U+003F '?' */
    0xf1, 0x24, 0x40, 0x40,
    /* U+0040 '@' */
    0x3e, 0x30, 0xb0, 0x33, 0x99, 0x5c, 0xfb, 0x00, 0xc4, 0x3c, 0x00,
    /* U+0041 'A' */
    0x10, 0x50, 0xa2, 0x27, 0xc8, 0xa0, 0x80,
    /* U+0042 'B' */
    0xf4, 0x63, 0xe8, 0xc7, 0xc0,
    /* U+0043 'C' */
    0x39, 0x18, 0x20, 0x81, 0x13, 0x80,
    /* U+0044 'D' */
    0xfa, 0x38, 0x61, 0x86, 0x3f, 0x80,
    /* U+0045 'E' */
    0xfc, 0x21, 0xf8, 0x43, 0xe0,
    /* U+0046 'F' */
    0xf8, 0x8f, 0x88, 0x80,
    /* U+0047 'G' */
    0x7b, 0x18, 0x27, 0x87, 0x17, 0x80,
    /* U+0048 'H' */
    0x86, 0x18, 0x7f, 0x86, 0x18, 0x40,
    /* U+0049 'I' */
    0xfe,
    /* U+004A 'J' */
    0x24, 0x92, 0x49, 0xc0,
    /* U+004B 'K' */
    0x8c, 0xa9, 0x8a, 0x4a, 0x20,
    /* U+004C 'L' */
    0x84, 0x21, 0x08, 0x43, 0xe0,
    /* U+004D 'M' */
    0x83, 0x8f, 0x1d, 0x5a, 0xb2, 0x60, 0x80,
    /* U+004E 'N' */
    0x87, 0x1a, 0x69, 0x96, 0x38, 0x40,
    /* U+004F 'O' */
    0x7b, 0x38, 0x61, 0x87, 0x37, 0x80,
    /* U+0050 'P' */
    0xf4, 0x63, 0xe8, 0x42, 0x00,
    /* U+0051 'Q' */
    0x7b, 0x38, 0x61, 0x87, 0x27, 0x02,
    /* U+0052 'R' */
    0xf2, 0x28, 0xbc, 0x92, 0x28, 0x40,
    /* U+0053 'S' */
    0x74, 0x60, 0xe0, 0xc5, 0xc0,
    /* U+0054 'T' */
    0xf9, 0x08, 0x42, 0x10, 0x80,
    /* U+0055 'U' */
    0x86, 0x18, 0x61, 0x86, 0x17, 0x80,
    /* U+0056 'V' */
    0x83, 0x05, 0x12, 0x22, 0x85, 0x04, 0x00,
    /* U+0057 'W' */
    0x88, 0xc4, 0x55, 0x4a, 0xa5, 0x51, 0x10, 0x88,
    /* U+0058 'X' */
    0xcd, 0x23, 0x0c, 0x31, 0x2c, 0xc0,
    /* U+0059 'Y' */
    0x82, 0x88, 0xa0, 0x81, 0x02, 0x04, 0x00,
    /* U+005A 'Z' */
    0xfc, 0x21, 0x0c, 0x21, 0x0f, 0xc0,
    /* U+005B '[' */
    0xea, 0xaa, 0xc0,
    /* U+005C */
    0x91, 0x24, 0x89,
    /* U+005D ']' */
    0xd5, 0x55, 0xc0,
    /* U+005E '^' */
    0x31, 0x28, 0x40,
    /* U+005F '_' */
    0xf8,
    /* U+0060 '`' */
    0x90,
    /* U+0061 'a' */
    0x70, 0x5f, 0x1f, 0x80,
    /* U+0062 'b' */
    0x84, 0x21, 0xe8, 0xc6, 0x3e,
    /* U+0063 'c' */
    0x78, 0x88, 0x70,
    /* U+0064 'd' */
    0x08, 0x42, 0xf8, 0xc6, 0x2f,
    /* U+0065 'e' */
    0x74, 0x7f, 0x07, 0x80,
    /* U+0066 'f' */
    0x74, 0x4e, 0x44, 0x44,
    /* U+0067 'g' */
    0x7c, 0x63, 0x17, 0x85, 0xc0,
    /* U+0068 'h' */
    0x84, 0x21, 0xe8, 0xc6, 0x31,
    /* U+0069 'i' */
    0x9f,
    /* U+006A 'j' */
    0x41, 0x55, 0x70,
    /* U+006B 'k' */
    0x88, 0x89, 0xac, 0xa9,
    /* U+006C 'l' */
    0xff,
    /* U+006D 'm' */
    0xf7, 0x44, 0x62, 0x31, 0x18, 0x88,
    /* U+006E 'n' */
    0xf4, 0x63, 0x18, 0x80,
    /* U+006F 'o' */
    0x74, 0x63, 0x17, 0x00,
    /* U+0070 'p' */
    0xf4, 0x63, 0x1f, 0x42, 0x00,
    /* U+0071 'q' */
    0x7c, 0x63, 0x17, 0x84, 0x20,
    /* U+0072 'r' */
    0xf2, 0x48,
    /* U+0073 's' */
    0xf8, 0x71, 0xf0,
    /* U+0074 't' */
    0x44, 0xf4, 0x44, 0x70,
    /* U+0075 'u' */
    0x8c, 0x63, 0x17, 0x80,
    /* U+0076 'v' */
    0x8c, 0x54, 0xa2, 0x00,
    /* U+0077 'w' */
    0x93, 0x56, 0xaa, 0x24, 0x40,
    /* U+0078 'x' */
    0x8a, 0x88, 0xa8, 0x80,
    /* U+0079 'y' */
    0x8c, 0x54, 0xa2, 0x13, 0x00,
    /* U+007A 'z' */
    0xf1, 0x24, 0xf0,
    /* U+007B '{' */
    0x32, 0x22, 0xc2, 0x22, 0x30,
    /* U+007C '|' */
    0xff, 0xc0,
    /* U+007D '}' */
    0xc4, 0x44, 0x34, 0x44, 0xc0,
    /* U+007E '~' */
    0x66, 0x60,
    /* U+00B0 '°' */
    0xf7, 0x80,
    /* U+00B5 'µ' */
    0x8a, 0x28, 0xa2, 0xfe, 0x08, 0x00,
    /* U+00B7 '·' */
    0x80,
    /* U+00C0 'À' */
    0x20, 0x20, 0x00, 0x82, 0x85, 0x11, 0x3e, 0x45, 0x04,
    /* U+00C1 'Á' */
    0x08, 0x20, 0x00, 0x82, 0x85, 0x11, 0x3e, 0x45, 0x04,
    /* U+00C2 'Â' */
    0x10, 0x50, 0x00, 0x82, 0x85, 0x11, 0x3e, 0x45, 0x04,
    /* U+00C3 'Ã' */
    0x18, 0x60, 0x00, 0x82, 0x85, 0x11, 0x3e, 0x45, 0x04,
    /* U+00C7 'Ç' */
    0x39, 0x18, 0x20, 0x81, 0x13, 0x88, 0x60,
    /* U+00C9 'É' */
    0x11, 0x01, 0xf8, 0x43, 0xf0, 0x87, 0xc0,
    /* U+00CA 'Ê' */
    0x22, 0x81, 0xf8, 0x43, 0xf0, 0x87, 0xc0,
    /* U+00CD 'Í' */
    0x62, 0xaa, 0xa0,
    /* U+00D3 'Ó' */
    0x10, 0x80, 0x1e, 0xce, 0x18, 0x61, 0xcd, 0xe0,
    /* U+00D4 'Ô' */
    0x31, 0x20, 0x1e, 0xce, 0x18, 0x61, 0xcd, 0xe0,
    /* U+00D5 'Õ' */
    0x29, 0x40, 0x1e, 0xce, 0x18, 0x61, 0xcd, 0xe0,
    /* U+00D7 '×' */
    0x85, 0x23, 0x0c, 0x4a, 0x10,
    /* U+00DA 'Ú' */
    0x10, 0x80, 0x21, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00DC 'Ü' */
    0x48, 0x08, 0x61, 0x86, 0x18, 0x61, 0x78,
    /* U+00E0 'à' */
    0x41, 0x00, 0xe0, 0xbe, 0x3f,
    /* U+00E1 'á' */
    0x11, 0x00, 0xe0, 0xbe, 0x3f,
    /* U+00E2 'â' */
    0x22, 0x80, 0xe0, 0xbe, 0x3f,
    /* U+00E3 'ã' */
    0xed, 0xc0, 0xe0, 0xbe, 0x3f,
    /* U+00E7 'ç' */
    0x78, 0x88, 0x72, 0x60,
    /* U+00E9 'é' */
    0x11, 0x00, 0xe8, 0xfe, 0x0f,
    /* U+00EA 'ê' */
    0x22, 0x80, 0xe8, 0xfe, 0x0f,
    /* U+00ED 'í' */
    0x62, 0xaa,
    /* U+00F3 'ó' */
    0x11, 0x00, 0xe8, 0xc6, 0x2e,
    /* U+00F4 'ô' */
    0x22, 0x80, 0xe8, 0xc6, 0x2e,
    /* U+00F5 'õ' */
    0xed, 0xc0, 0xe8, 0xc6, 0x2e,
    /* U+00FA 'ú' */
    0x11, 0x01, 0x18, 0xc6, 0x2f,
    /* U+00FC 'ü' */
    0x50, 0x23, 0x18, 0xc5, 0xe0,
    /* U+2013 '–' */
    0xf0,
    /* U+2014 '—' */
    0xff, 0x80,
    /* U+2026 '…' */
    0x92,
    /* U+2212 '−' */
    0xfc,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* id 0: reserved */
    {.bitmap_index = 0, .adv_w = 48, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* U+0020 */
    {.bitmap_index = 0, .adv_w = 64, .box_w = 1, .box_h = 7, .ofs_x = 2, .ofs_y = 0}, /* U+0021 '!' */
    {.bitmap_index = 1, .adv_w = 80, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 4}, /* U+0022 '"' */
    {.bitmap_index = 3, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0023 '#' */
    {.bitmap_index = 10, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = -1}, /* U+0024 '$' */
    {.bitmap_index = 15, .adv_w = 160, .box_w = 8, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0025 '%' */
    {.bitmap_index = 22, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0026 '&' */
    {.bitmap_index = 29, .adv_w = 48, .box_w = 1, .box_h = 3, .ofs_x = 1, .ofs_y = 4}, /* U+0027 ''' */
    {.bitmap_index = 30, .adv_w = 64, .box_w = 2, .box_h = 9, .ofs_x = 1, .ofs_y = -1}, /* U+0028 '(' */
    {.bitmap_index = 33, .adv_w = 64, .box_w = 2, .box_h = 9, .ofs_x = 1, .ofs_y = -1}, /* U+0029 ')' */
    {.bitmap_index = 36, .adv_w = 80, .box_w = 5, .box_h = 4, .ofs_x = 0, .ofs_y = 3}, /* U+002A */
    {.bitmap_index = 39, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+002B '+' */
    {.bitmap_index = 46, .adv_w = 48, .box_w = 1, .box_h = 2, .ofs_x = 1, .ofs_y = -1}, /* U+002C ',' */
    {.bitmap_index = 47, .adv_w = 64, .box_w = 3, .box_h = 1, .ofs_x = 1, .ofs_y = 2}, /* U+002D '-' */
    {.bitmap_index = 48, .adv_w = 48, .box_w = 1, .box_h = 1, .ofs_x = 1, .ofs_y = 0}, /* U+002E '.' */
    {.bitmap_index = 49, .adv_w = 48, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1}, /* U+002F */
    {.bitmap_index = 52, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0030 '0' */
    {.bitmap_index = 57, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0031 '1' */
    {.bitmap_index = 62, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0032 '2' */
    {.bitmap_index = 67, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0033 '3' */
    {.bitmap_index = 72, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0034 '4' */
    {.bitmap_index = 77, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0035 '5' */
    {.bitmap_index = 82, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0036 '6' */
    {.bitmap_index = 87, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0037 '7' */
    {.bitmap_index = 92, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0038 '8' */
    {.bitmap_index = 97, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0039 '9' */
    {.bitmap_index = 102, .adv_w = 48, .box_w = 1, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+003A ':' */
    {.bitmap_index = 103, .adv_w = 48, .box_w = 1, .box_h = 6, .ofs_x = 1, .ofs_y = -1}, /* U+003B ';' */
    {.bitmap_index = 104, .adv_w = 128, .box_w = 6, .box_h = 5, .ofs_x = 1, .ofs_y = 1}, /* U+003C '<' */
    {.bitmap_index = 108, .adv_w = 128, .box_w = 6, .box_h = 3, .ofs_x = 1, .ofs_y = 2}, /* U+003D '=' */
    {.bitmap_index = 111, .adv_w = 128, .box_w = 6, .box_h = 5, .ofs_x = 1, .ofs_y = 1}, /* U+003E '>' */
    {.bitmap_index = 115, .adv_w = 80, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+003F '?' */
    {.bitmap_index = 119, .adv_w = 160, .box_w = 9, .box_h = 9, .ofs_x = 1, .ofs_y = -2}, /* U+0040 '@' */
    {.bitmap_index = 130, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0041 'A' */
    {.bitmap_index = 137, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0042 'B' */
    {.bitmap_index = 142, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0043 'C' */
    {.bitmap_index = 148, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0044 'D' */
    {.bitmap_index = 154, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0045 'E' */
    {.bitmap_index = 159, .adv_w = 96, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0046 'F' */
    {.bitmap_index = 163, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0047 'G' */
    {.bitmap_index = 169, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0048 'H' */
    {.bitmap_index = 175, .adv_w = 48, .box_w = 1, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0049 'I' */
    {.bitmap_index = 176, .adv_w = 48, .box_w = 3, .box_h = 9, .ofs_x = -1, .ofs_y = -2}, /* U+004A 'J' */
    {.bitmap_index = 180, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+004B 'K' */
    {.bitmap_index = 185, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+004C 'L' */
    {.bitmap_index = 190, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+004D 'M' */
    {.bitmap_index = 197, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+004E 'N' */
    {.bitmap_index = 203, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+004F 'O' */
    {.bitmap_index = 209, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0050 'P' */
    {.bitmap_index = 214, .adv_w = 128, .box_w = 6, .box_h = 8, .ofs_x = 1, .ofs_y = -1}, /* U+0051 'Q' */
    {.bitmap_index = 220, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0052 'R' */
    {.bitmap_index = 226, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0053 'S' */
    {.bitmap_index = 231, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0054 'T' */
    {.bitmap_index = 236, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+0055 'U' */
    {.bitmap_index = 242, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = -1, .ofs_y = 0}, /* U+0056 'V' */
    {.bitmap_index = 249, .adv_w = 160, .box_w = 9, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0057 'W' */
    {.bitmap_index = 257, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0058 'X' */
    {.bitmap_index = 263, .adv_w = 96, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0059 'Y' */
    {.bitmap_index = 270, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+005A 'Z' */
    {.bitmap_index = 276, .adv_w = 64, .box_w = 2, .box_h = 9, .ofs_x = 1, .ofs_y = -1}, /* U+005B '[' */
    {.bitmap_index = 279, .adv_w = 48, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = -1}, /* U+005C */
    {.bitmap_index = 282, .adv_w = 64, .box_w = 2, .box_h = 9, .ofs_x = 1, .ofs_y = -1}, /* U+005D ']' */
    {.bitmap_index = 285, .adv_w = 128, .box_w = 6, .box_h = 3, .ofs_x = 1, .ofs_y = 4}, /* U+005E '^' */
    {.bitmap_index = 288, .adv_w = 80, .box_w = 5, .box_h = 1, .ofs_x = 0, .ofs_y = -2}, /* U+005F '_' */
    {.bitmap_index = 289, .adv_w = 80, .box_w = 2, .box_h = 2, .ofs_x = 1, .ofs_y = 6}, /* U+0060 '`' */
    {.bitmap_index = 290, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0061 'a' */
    {.bitmap_index = 294, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0062 'b' */
    {.bitmap_index = 299, .adv_w = 96, .box_w = 4, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0063 'c' */
    {.bitmap_index = 302, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0064 'd' */
    {.bitmap_index = 307, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0065 'e' */
    {.bitmap_index = 311, .adv_w = 64, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0066 'f' */
    {.bitmap_index = 315, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = -2}, /* U+0067 'g' */
    {.bitmap_index = 320, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0068 'h' */
    {.bitmap_index = 325, .adv_w = 48, .box_w = 1, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0069 'i' */
    {.bitmap_index = 326, .adv_w = 48, .box_w = 2, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+006A 'j' */
    {.bitmap_index = 329, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+006B 'k' */
    {.bitmap_index = 333, .adv_w = 48, .box_w = 1, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+006C 'l' */
    {.bitmap_index = 334, .adv_w = 160, .box_w = 9, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+006D 'm' */
    {.bitmap_index = 340, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+006E 'n' */
    {.bitmap_index = 344, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+006F 'o' */
    {.bitmap_index = 348, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = -2}, /* U+0070 'p' */
    {.bitmap_index = 353, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = -2}, /* U+0071 'q' */
    {.bitmap_index = 358, .adv_w = 64, .box_w = 3, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0072 'r' */
    {.bitmap_index = 360, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0073 's' */
    {.bitmap_index = 363, .adv_w = 64, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0074 't' */
    {.bitmap_index = 367, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0075 'u' */
    {.bitmap_index = 371, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0076 'v' */
    {.bitmap_index = 375, .adv_w = 128, .box_w = 7, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0077 'w' */
    {.bitmap_index = 380, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+0078 'x' */
    {.bitmap_index = 384, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = -2}, /* U+0079 'y' */
    {.bitmap_index = 389, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 1, .ofs_y = 0}, /* U+007A 'z' */
    {.bitmap_index = 392, .adv_w = 96, .box_w = 4, .box_h = 9, .ofs_x = 1, .ofs_y = -1}, /* U+007B '{' */
    {.bitmap_index = 397, .adv_w = 48, .box_w = 1, .box_h = 10, .ofs_x = 1, .ofs_y = -2}, /* U+007C '|' */
    {.bitmap_index = 399, .adv_w = 96, .box_w = 4, .box_h = 9, .ofs_x = 1, .ofs_y = -1}, /* U+007D '}' */
    {.bitmap_index = 404, .adv_w = 128, .box_w = 6, .box_h = 2, .ofs_x = 1, .ofs_y = 3}, /* U+007E '~' */
    {.bitmap_index = 406, .adv_w = 80, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 4}, /* U+00B0 '°' */
    {.bitmap_index = 408, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = -2}, /* U+00B5 'µ' */
    {.bitmap_index = 414, .adv_w = 48, .box_w = 1, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+00B7 '·' */
    {.bitmap_index = 415, .adv_w = 112, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+00C0 'À' */
    {.bitmap_index = 424, .adv_w = 112, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+00C1 'Á' */
    {.bitmap_index = 433, .adv_w = 112, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+00C2 'Â' */
    {.bitmap_index = 442, .adv_w = 112, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+00C3 'Ã' */
    {.bitmap_index = 451, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = -2}, /* U+00C7 'Ç' */
    {.bitmap_index = 458, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00C9 'É' */
    {.bitmap_index = 465, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00CA 'Ê' */
    {.bitmap_index = 472, .adv_w = 48, .box_w = 2, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00CD 'Í' */
    {.bitmap_index = 475, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00D3 'Ó' */
    {.bitmap_index = 483, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00D4 'Ô' */
    {.bitmap_index = 491, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00D5 'Õ' */
    {.bitmap_index = 499, .adv_w = 128, .box_w = 6, .box_h = 6, .ofs_x = 1, .ofs_y = 0}, /* U+00D7 '×' */
    {.bitmap_index = 504, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0}, /* U+00DA 'Ú' */
    {.bitmap_index = 512, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0}, /* U+00DC 'Ü' */
    {.bitmap_index = 519, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00E0 'à' */
    {.bitmap_index = 524, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00E1 'á' */
    {.bitmap_index = 529, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00E2 'â' */
    {.bitmap_index = 534, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00E3 'ã' */
    {.bitmap_index = 539, .adv_w = 96, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = -2}, /* U+00E7 'ç' */
    {.bitmap_index = 543, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00E9 'é' */
    {.bitmap_index = 548, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00EA 'ê' */
    {.bitmap_index = 553, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00ED 'í' */
    {.bitmap_index = 555, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00F3 'ó' */
    {.bitmap_index = 560, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00F4 'ô' */
    {.bitmap_index = 565, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00F5 'õ' */
    {.bitmap_index = 570, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+00FA 'ú' */
    {.bitmap_index = 575, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0}, /* U+00FC 'ü' */
    {.bitmap_index = 580, .adv_w = 80, .box_w = 4, .box_h = 1, .ofs_x = 0, .ofs_y = 2}, /* U+2013 '–' */
    {.bitmap_index = 581, .adv_w = 160, .box_w = 9, .box_h = 1, .ofs_x = 0, .ofs_y = 2}, /* U+2014 '—' */
    {.bitmap_index = 583, .adv_w = 160, .box_w = 7, .box_h = 1, .ofs_x = 1, .ofs_y = 0}, /* U+2026 '…' */
    {.bitmap_index = 584, .adv_w = 128, .box_w = 6, .box_h = 1, .ofs_x = 1, .ofs_y = 3}, /* U+2212 '−' */
};

static const uint16_t unicode_list[] = {
    0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008, 0x0009, 0x000a, 0x000b,
    0x000c, 0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0012, 0x0013, 0x0014, 0x0015, 0x0016, 0x0017,
    0x0018, 0x0019, 0x001a, 0x001b, 0x001c, 0x001d, 0x001e, 0x001f, 0x0020, 0x0021, 0x0022, 0x0023,
    0x0024, 0x0025, 0x0026, 0x0027, 0x0028, 0x0029, 0x002a, 0x002b, 0x002c, 0x002d, 0x002e, 0x002f,
    0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003a, 0x003b,
    0x003c, 0x003d, 0x003e, 0x003f, 0x0040, 0x0041, 0x0042, 0x0043, 0x0044, 0x0045, 0x0046, 0x0047,
    0x0048, 0x0049, 0x004a, 0x004b, 0x004c, 0x004d, 0x004e, 0x004f, 0x0050, 0x0051, 0x0052, 0x0053,
    0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b, 0x005c, 0x005d, 0x005e, 0x0090,
    0x0095, 0x0097, 0x00a0, 0x00a1, 0x00a2, 0x00a3, 0x00a7, 0x00a9, 0x00aa, 0x00ad, 0x00b3, 0x00b4,
    0x00b5, 0x00b7, 0x00ba, 0x00bc, 0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c7, 0x00c9, 0x00ca, 0x00cd,
    0x00d3, 0x00d4, 0x00d5, 0x00da, 0x00dc, 0x1ff3, 0x1ff4, 0x2006, 0x21f2,
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 0x0020, .range_length = 8691, .glyph_id_start = 1, .unicode_list = unicode_list, .glyph_id_ofs_list = NULL, .list_length = 129, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,
    .stride = 0,
};

const lv_font_t ui_font_r10 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 13,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};
