#!/usr/bin/env python3
"""Preenche os planos de terra com o preenchedor do proprio KiCad.

The generators here write a zone as an outline and nothing else, which is a
legal board file - KiCad fills a zone when it opens it. But `kicad-cli pcb
drc` does NOT fill, and a DRC run on an unfilled board is not the check it
looks like:

  * every ground pad that reaches the plane and nothing else is reported as
    unconnected (204 of the 296 ratlines), and every stitching via as
    dangling (180 of them), because the copper that connects them is not in
    the file yet;
  * and no clearance is ever measured against the pour, so the check that
    matters most for a board covered in ground is the one that never runs.

So the fill is done here, by `pcbnew`, which is the same filler the editor
uses - not an approximation of it. This is the only script in the chain that
writes the board through KiCad instead of by hand, and KiCad rewrites the
whole file in its own formatting when it saves.

    "D:/KiCAD/bin/python.exe" hardware_gnssbike/cad/fill_zones.py

It has to run with KiCad's own interpreter: `pcbnew` is a compiled module
that lives next to the program, not a package that pip installs.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent


def main() -> int:
    try:
        import pcbnew
    except ImportError:
        print("pcbnew nao esta neste interpretador: rode com o Python do "
              'KiCad, "D:/KiCAD/bin/python.exe"', file=sys.stderr)
        return 2

    caminho = HERE / "gnssbike.kicad_pcb"
    # pcbnew opens the whole PROJECT, and on the way out it rewrites the
    # .kicad_pro with every default spelled in full and drops a .kicad_prl of
    # local editor state beside it. Neither has anything to do with filling a
    # zone, and the .kicad_pro is generated by make_pro.py - letting KiCad
    # rewrite it means the two fight over the file on every run. So it is put
    # back byte for byte and the .prl is removed.
    projeto = HERE / "gnssbike.kicad_pro"
    antes = projeto.read_bytes() if projeto.exists() else None
    prl = HERE / "gnssbike.kicad_prl"
    tinha_prl = prl.exists()
    placa = pcbnew.LoadBoard(str(caminho))
    zonas = placa.Zones()
    preenchedor = pcbnew.ZONE_FILLER(placa)
    ok = preenchedor.Fill(zonas)
    # a rule area is a zone too, and it has no copper to fill: counting it
    # as a zone that failed to fill is how this reported 3 of 7
    despejos = [z for z in zonas if not z.GetIsRuleArea()]
    cheias = sum(1 for z in despejos if z.IsFilled())
    placa.Save(str(caminho))
    if antes is not None:
        projeto.write_bytes(antes)
    if prl.exists() and not tinha_prl:
        prl.unlink()
    print(f"{len(despejos)} despejos de cobre, {cheias} preenchidos, "
          f"{len(zonas) - len(despejos)} areas de regra"
          f"{'' if ok else ' (o preenchedor reclamou)'}")
    return 0 if ok and cheias == len(despejos) else 1


if __name__ == "__main__":
    raise SystemExit(main())
